<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LocaluspSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locais = [
            ['codlocusp' => 4115, 'setor' => 'LAMEM', 'nome' => 'Lamem Secretaria'],
            ['codlocusp' => 4117, 'setor' => 'LAMEM', 'nome' => ''],
            ['codlocusp' => 4119, 'setor' => 'LAMEM', 'nome' => 'Lamem Sala Multimidia - Roberto'],
            ['codlocusp' => 4122, 'setor' => 'LAMEM', 'nome' => 'LAMEM-Base de Dados'],
            ['codlocusp' => 4123, 'setor' => 'LAMEM', 'nome' => 'Lamem - Sala de Rack'],
            ['codlocusp' => 4124, 'setor' => 'LAMEM', 'nome' => 'Sala granulometria JENIK'],
            ['codlocusp' => 4125, 'setor' => 'LAMEM', 'nome' => 'Lamem-almoxarifado'],
            ['codlocusp' => 4126, 'setor' => 'LAMEM', 'nome' => 'Lamem Sala Climatizada'],
            ['codlocusp' => 4127, 'setor' => 'LAMEM', 'nome' => 'LAMEM - Colagem'],
            ['codlocusp' => 4132, 'setor' => 'LAMEM', 'nome' => 'Sala de Reuniões'],
            ['codlocusp' => 4324, 'setor' => 'LAMEM', 'nome' => 'LAMEM Salão de Ensaios'],
            ['codlocusp' => 4347, 'setor' => 'LAMEM', 'nome' => ''],
            ['codlocusp' => 4348, 'setor' => 'LAMEM', 'nome' => 'Lamem sala'],
            ['codlocusp' => 4349, 'setor' => 'LAMEM', 'nome' => 'LAMEM-Alunos 08'],
            ['codlocusp' => 4350, 'setor' => 'LAMEM', 'nome' => ''],
            ['codlocusp' => 4352, 'setor' => 'LAMEM', 'nome' => ''],
            ['codlocusp' => 4353, 'setor' => 'LAMEM', 'nome' => 'LAMEM-Alunos'],
            ['codlocusp' => 4354, 'setor' => 'LAMEM', 'nome' => 'Lamem - Alunos'],
            ['codlocusp' => 4355, 'setor' => 'LAMEM', 'nome' => 'Sala Lamem'],
            ['codlocusp' => 4356, 'setor' => 'LAMEM', 'nome' => 'LAMEM-Alunos'],
            ['codlocusp' => 4357, 'setor' => 'LAMEM', 'nome' => 'LAMEM-Pós Doutorandos'],
            ['codlocusp' => 4358, 'setor' => 'LAMEM', 'nome' => 'Prof Francisco Antonio ROCCO Lahr'],
            ['codlocusp' => 4359, 'setor' => 'LAMEM', 'nome' => 'Prof Antonio Alves Dias'],
            ['codlocusp' => 4360, 'setor' => 'LAMEM', 'nome' => 'Prof Calil2'],
            ['codlocusp' => 4361, 'setor' => 'LAMEM', 'nome' => 'Prof Carlito CALIL Junior'],
            ['codlocusp' => 4362, 'setor' => 'LAMEM', 'nome' => 'Sala de aula'],
            ['codlocusp' => 4363, 'setor' => 'LAMEM', 'nome' => ''],
            ['codlocusp' => 4366, 'setor' => 'LAMEM', 'nome' => ''],
            ['codlocusp' => 4367, 'setor' => 'LAMEM', 'nome' => ''],
            ['codlocusp' => 20307, 'setor' => 'LAMEM', 'nome' => 'lamem salao'],
            ['codlocusp' => 21348, 'setor' => 'LMABC', 'nome' => ''],
            ['codlocusp' => 21918, 'setor' => 'LMABC', 'nome' => 'LMABC-Alunos 2'],
            ['codlocusp' => 21948, 'setor' => 'LMABC', 'nome' => 'LMABC Salas'],
            ['codlocusp' => 26490, 'setor' => 'LMABC', 'nome' => 'LMABC Bolsistas superior'],
            ['codlocusp' => 2118, 'setor' => 'SET', 'nome' => ''],
            ['codlocusp' => 2767, 'setor' => 'SET', 'nome' => 'Secretaria'],
            ['codlocusp' => 2778, 'setor' => 'SET', 'nome' => 'Sala de Aula SET01'],
            ['codlocusp' => 2779, 'setor' => 'SET', 'nome' => 'Hall térreo'],
            ['codlocusp' => 2780, 'setor' => 'SET', 'nome' => 'Sanitário (M)-Térreo'],
            ['codlocusp' => 2781, 'setor' => 'SET', 'nome' => 'Sanitário (F)-Térreo'],
            ['codlocusp' => 2782, 'setor' => 'SET', 'nome' => 'Copa'],
            ['codlocusp' => 2783, 'setor' => 'SET', 'nome' => 'Estar térreo'],
            ['codlocusp' => 2785, 'setor' => 'SET', 'nome' => 'Sala de aula SET02'],
            ['codlocusp' => 2786, 'setor' => 'SET', 'nome' => 'LE - Laboratório de estruturas'],
            ['codlocusp' => 2787, 'setor' => 'SET', 'nome' => 'LE - Sala dos Técnicos'],
            ['codlocusp' => 2788, 'setor' => 'SET', 'nome' => 'LE - Câmara Climatizada'],
            ['codlocusp' => 2817, 'setor' => 'SET', 'nome' => 'LE - Câmara Úmida'],
            ['codlocusp' => 2819, 'setor' => 'SET', 'nome' => 'LE - Vestiário'],
            ['codlocusp' => 2821, 'setor' => 'SET', 'nome' => 'LE - Oficina Mecânica'],
            ['codlocusp' => 2828, 'setor' => 'SET', 'nome' => 'Sanitário (SUB SOLO)'],
            ['codlocusp' => 2829, 'setor' => 'SET', 'nome' => 'HALL-Subsolo'],
            ['codlocusp' => 2830, 'setor' => 'SET', 'nome' => 'Sala de aula SET03 (Subsolo)'],
            ['codlocusp' => 2831, 'setor' => 'SET', 'nome' => 'Auditório'],
            ['codlocusp' => 2834, 'setor' => 'SET', 'nome' => 'LIMC Processamento'],
            ['codlocusp' => 2836, 'setor' => 'SET', 'nome' => 'LIMC Masaki'],
            ['codlocusp' => 2837, 'setor' => 'SET', 'nome' => 'Prof Walter SAVASSI'],
            ['codlocusp' => 2838, 'setor' => 'SET', 'nome' => 'Prof ANA Lucia'],
            ['codlocusp' => 2841, 'setor' => 'SET', 'nome' => 'Mestrado 3'],
            ['codlocusp' => 2842, 'setor' => 'SET', 'nome' => 'Mestrado 4'],
            ['codlocusp' => 2843, 'setor' => 'SET', 'nome' => 'Mestrado 5'],
            ['codlocusp' => 2845, 'setor' => 'SET', 'nome' => 'Mestrado 6'],
            ['codlocusp' => 2846, 'setor' => 'SET', 'nome' => 'Mestrado 7'],
            ['codlocusp' => 2847, 'setor' => 'SET', 'nome' => 'Mestrado 8'],
            ['codlocusp' => 2848, 'setor' => 'SET', 'nome' => 'Mestrado 1'],
            ['codlocusp' => 2850, 'setor' => 'SET', 'nome' => 'Mestrado 9'],
            ['codlocusp' => 2854, 'setor' => 'SET', 'nome' => 'Prof LIBÂNIO Miranda Pinheiro'],
            ['codlocusp' => 2855, 'setor' => 'SET', 'nome' => 'LE - sonelastic'],
            ['codlocusp' => 2861, 'setor' => 'SET', 'nome' => 'SACIVIL'],
            ['codlocusp' => 2863, 'setor' => 'SET', 'nome' => 'Prof André Teófilo Beck'],
            ['codlocusp' => 2865, 'setor' => 'SET', 'nome' => 'Prof MOUNIR El Debs'],
            ['codlocusp' => 2869, 'setor' => 'SET', 'nome' => 'Prof José Elias LAIER'],
            ['codlocusp' => 2870, 'setor' => 'SET', 'nome' => 'Prof Rodolfo André Kuche Sanches'],
            ['codlocusp' => 2872, 'setor' => 'SET', 'nome' => 'Prof Marcio CORREA'],
            ['codlocusp' => 2873, 'setor' => 'SET', 'nome' => 'Sanitário (M) -Superior'],
            ['codlocusp' => 2874, 'setor' => 'SET', 'nome' => ''],
            ['codlocusp' => 2876, 'setor' => 'SET', 'nome' => 'Sanitário (F)-Superior'],
            ['codlocusp' => 2877, 'setor' => 'SET', 'nome' => 'Limpeza - Depósito (SUP)'],
            ['codlocusp' => 2888, 'setor' => 'SET', 'nome' => 'LIMC Sala de Impressão'],
            ['codlocusp' => 2890, 'setor' => 'SET', 'nome' => 'LIMC - Dorival'],
            ['codlocusp' => 2891, 'setor' => 'SET', 'nome' => 'Pós Doutorandos 1??'],
            ['codlocusp' => 2893, 'setor' => 'SET', 'nome' => 'Prof Rodrigo Ribeiro PACCOLA'],
            ['codlocusp' => 2895, 'setor' => 'SET', 'nome' => 'Sala de reuniões - sup.'],
            ['codlocusp' => 2896, 'setor' => 'SET', 'nome' => 'Deposito setor 1'],
            ['codlocusp' => 2897, 'setor' => 'SET', 'nome' => 'Profa Marcela Novischi Kataoka'],
            ['codlocusp' => 2899, 'setor' => 'SET', 'nome' => 'Prof EDSON Denner Leonel'],
            ['codlocusp' => 2900, 'setor' => 'SET', 'nome' => 'Prof Vladimir Guilherme Haach'],
            ['codlocusp' => 2903, 'setor' => 'SET', 'nome' => 'Prof Ricardo CARRAZEDO'],
            ['codlocusp' => 2904, 'setor' => 'SET', 'nome' => 'Prof José JAIRO de Sáles'],
            ['codlocusp' => 2906, 'setor' => 'SET', 'nome' => 'LIMC Deposito'],
            ['codlocusp' => 2907, 'setor' => 'SET', 'nome' => 'Prof MAXimiliano Malite'],
            ['codlocusp' => 2908, 'setor' => 'SET', 'nome' => 'Prof JORGE Munaiar Neto'],
            ['codlocusp' => 2910, 'setor' => 'SET', 'nome' => 'Prof Marcio RAMALHO'],
            ['codlocusp' => 2911, 'setor' => 'SET', 'nome' => 'Antigo Prof Samuel'],
            ['codlocusp' => 2912, 'setor' => 'SET', 'nome' => 'Prof Visitante 3'],
            ['codlocusp' => 2914, 'setor' => 'SET', 'nome' => 'Prof Roberto L A BARBATO'],
            ['codlocusp' => 2915, 'setor' => 'SET', 'nome' => 'Prof ADAIR Aguiar'],
            ['codlocusp' => 2918, 'setor' => 'SET', 'nome' => 'Prof João Batista de PAIVA'],
            ['codlocusp' => 2919, 'setor' => 'SET', 'nome' => 'Prof Alessandra Castro'],
            ['codlocusp' => 2921, 'setor' => 'SET', 'nome' => 'Prof Rogério Carrazedo'],
            ['codlocusp' => 2922, 'setor' => 'SET', 'nome' => 'Visitante 6'],
            ['codlocusp' => 2923, 'setor' => 'SET', 'nome' => 'Prof Humberto Breves CODA'],
            ['codlocusp' => 2926, 'setor' => 'SET', 'nome' => 'LIMC Técnicos'],
            ['codlocusp' => 2931, 'setor' => 'SET', 'nome' => 'LIMC Sala de Servidores'],
            ['codlocusp' => 2935, 'setor' => 'SET', 'nome' => 'Francisco Brito'],
            ['codlocusp' => 2936, 'setor' => 'SET', 'nome' => 'LIMC WEB - Melina'],
            ['codlocusp' => 2943, 'setor' => 'SET', 'nome' => 'LE - Sala Vareda'],
            ['codlocusp' => 2945, 'setor' => 'SET', 'nome' => 'LE - Galpão de ensaios'],
            ['codlocusp' => 3969, 'setor' => 'SET', 'nome' => 'Sala de reuniões - térreo'],
            ['codlocusp' => 5418, 'setor' => 'SET', 'nome' => 'LIMC Manutenção'],
            ['codlocusp' => 5451, 'setor' => 'SET', 'nome' => 'LE - Depósito de ferramentas'],
            ['codlocusp' => 5452, 'setor' => 'SET', 'nome' => 'LE - Depósito de ferramentas 2'],
            ['codlocusp' => 5785, 'setor' => 'SET', 'nome' => 'LE - Depósito piso superior'],
            ['codlocusp' => 5786, 'setor' => 'SET', 'nome' => 'LE - Sala de reunião piso superior'],
            ['codlocusp' => 5787, 'setor' => 'SET', 'nome' => 'LE - Casa de bomba instron 1'],
            ['codlocusp' => 5788, 'setor' => 'SET', 'nome' => 'LE - Instron 1'],
            ['codlocusp' => 5789, 'setor' => 'SET', 'nome' => 'LE - Instron 2'],
            ['codlocusp' => 5790, 'setor' => 'SET', 'nome' => 'Prof SERGIO Proença'],
            ['codlocusp' => 5791, 'setor' => 'SET', 'nome' => 'Deposito setor 3'],
            ['codlocusp' => 21194, 'setor' => 'SET', 'nome' => 'Doutorandos'],
            ['codlocusp' => 21195, 'setor' => 'SET', 'nome' => 'WC Feminino deficiente subsolo'],
            ['codlocusp' => 21198, 'setor' => 'SET', 'nome' => 'LIMC Ensino Informatizado'],
            ['codlocusp' => 21199, 'setor' => 'SET', 'nome' => 'LE - Área externa para concretagem'],
            ['codlocusp' => 21345, 'setor' => 'SET', 'nome' => 'WC Feminino subsolo'],
            ['codlocusp' => 21391, 'setor' => 'SET', 'nome' => 'Mestrado 2'],
            ['codlocusp' => 21465, 'setor' => 'SET', 'nome' => 'Prof JEFFERSON Libório'],
            ['codlocusp' => 21919, 'setor' => 'SET', 'nome' => 'LMABC-Alunos 1'],
            ['codlocusp' => 24372, 'setor' => 'SET', 'nome' => 'LE - Abrigo das máquinas'],
            ['codlocusp' => 8396, 'setor' => 'SVLIMAT', 'nome' => 'Local para materiais inserviveis'],
        ];
        \DB::table('localusps')->insert($locais);
    }
}
